### ISSUE TITLE
Manage HTTP Server on another package

### ISSUE THREAD

**Issue by Nicolas-ggd** [CyberRoute/bruter#32]
Hello, first of all it's a intrested project.

It's a better to remove HTTP server and routers from `cmd/bruter` and move `pkg/server` and `pkg/router`.

/cmd
    /app
      main.go
    /pkg
       /server
         server.go
    /router
         router.go

- pkg/server: this is where the HTTP server logic and configuration should be managed.
- pkg/router: this can handle all routing logic.

I think it's a more clear structure and easy to use, all over the application. 

If you are welcome about contribution i will do that.

**Comment by CyberRoute** [comment]
Hey Nicolas! Thanks a lot for looking into this ... happy to see contributions, of course if you wanna take it feel free to send a PR :)

**Comment by CyberRoute** [comment]
closing this out, thanks again @Nicolas-ggd
